tsukuba2016:main.cpp navigation.h navigation.cpp avoid.h avoid.cpp localization.h localization.cpp camera.h camera.cpp joystick.h joystick.cpp motor.h motor.cpp tsukuba_time.h tsukuba_time.cpp tsukuba_tkk.h tsukuba_tkk.cpp tsukuba_urg.h tsukuba_urg.cpp Makefile
	g++ -o tsukuba2016 main.cpp navigation.cpp avoid.cpp localization.cpp camera.cpp motor.cpp joystick.cpp tsukuba_time.cpp tsukuba_tkk.cpp tsukuba_urg.cpp Connection_information.cpp `pkg-config --libs opencv` `urg_cpp-config --cflags` `urg_cpp-config --libs` `pkg-config --cflags opencv` `pkg-config --libs opencv`

